---
name: Lingua-Abbreviate-Hierarchy
version: 0.04
author:
  - 'Andy Armstrong <andy@hexten.net>'
abstract: Shorten verbose namespaces
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Lingua-Abbreviate-Hierarchy
  license: http://dev.perl.org/licenses/
  repository: git://github.com/AndyA/Lingua--Abbreviate--Hierarchy.git
requires:
  Test::Differences: 0
  Test::More: 0
provides:
  Lingua::Ab::H:
    file: lib/Lingua/Ab/H.pm
    version: 0.04
  Lingua::Abbreviate::Hierarchy:
    file: lib/Lingua/Abbreviate/Hierarchy.pm
    version: 0.04
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
